// var alphabet = [
//   {letter: "a", img: "a.jpg"},
//   {letter: "b", img: "b.jpg"},
//   {letter: "c", img: "c.jpg"},
//   {letter: "d", img: "d.jpg"},
//   {letter: "e", img: "e.jpg"},
//   {letter: "f", img: "f.jpg"},
//   {letter: "g", img: "g.jpg"},
//   {letter: "h", img: "h.jpg"},
//   {letter: "i", img: "i.jpg"},
//   {letter: "j", img: "j.jpg"},
//   {letter: "k", img: "k.jpg"},
//   {letter: "l", img: "l.jpg"},
//   {letter: "m", img: "m.jpg"},
//   {letter: "n", img: "n.jpg"},
//   {letter: "o", img: "o.jpg"},
//   {letter: "p", img: "p.jpg"},
//   {letter: "q", img: "q.jpg"},
//   {letter: "r", img: "r.jpg"},
//   {letter: "s", img: "s.jpg"},
//   {letter: "t", img: "t.jpg"},
//   {letter: "u", img: "u.jpg"},
//   {letter: "v", img: "v.jpg"},
//   {letter: "w", img: "w.jpg"},
//   {letter: "x", img: "x.jpg"},
//   {letter: "y", img: "y.jpg"},
//   {letter: "z", img: "z.jpg"}
//   ];

var alphabet = {
  a: "a.jpg",
  b: "b.jpg",
  c: "c.jpg",
  d: "d.jpg",
  e: "e.jpg",
  f: "f.jpg",
  g: "g.jpg",
  h: "h.jpg",
  i: "i.jpg",
  j: "j.jpg",
  k: "k.jpg",
  l: "l.jpg",
  m: "m.jpg",
  n: "n.jpg",
  o: "o.jpg",
  p: "p.jpg",
  q: "q.jpg",
  r: "r.jpg",
  s: "s.jpg",
  t: "t.jpg",
  u: "u.jpg",
  v: "v.jpg",
  w: "w.jpg",
  x: "x.jpg",
  y: "y.jpg",
  z: "z.jpg"
};
