var alphabet = {
  a: "images/a.jpg",
  b: "images/b.jpg",
  c: "images/c.jpg",
  d: "images/d.jpg",
  e: "images/e.jpg",
  f: "images/f.jpg",
  g: "images/g.jpg",
  h: "images/h.jpg",
  i: "images/i.jpg",
  j: "images/j.jpg",
  k: "images/k.jpg",
  l: "images/l.jpg",
  m: "images/m.jpg",
  n: "images/n.jpg",
  o: "images/o.jpg",
  p: "images/p.jpg",
  q: "images/q.jpg",
  r: "images/r.jpg",
  s: "images/s.jpg",
  t: "images/t.jpg",
  u: "images/u.jpg",
  v: "images/v.jpg",
  w: "images/w.jpg",
  x: "images/x.jpg",
  y: "images/y.jpg",
  z: "images/z.jpg"
};
